//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrograV_Clase8.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CustomerEntites : DbContext
    {
        public CustomerEntites()
            : base("name=CustomerEntites")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
    
        public virtual int sp_CreateCustomer(string p_CustomerName, string p_LastName, string p_Country, Nullable<int> p_Age, Nullable<int> p_Phone)
        {
            var p_CustomerNameParameter = p_CustomerName != null ?
                new ObjectParameter("P_CustomerName", p_CustomerName) :
                new ObjectParameter("P_CustomerName", typeof(string));
    
            var p_LastNameParameter = p_LastName != null ?
                new ObjectParameter("P_LastName", p_LastName) :
                new ObjectParameter("P_LastName", typeof(string));
    
            var p_CountryParameter = p_Country != null ?
                new ObjectParameter("P_Country", p_Country) :
                new ObjectParameter("P_Country", typeof(string));
    
            var p_AgeParameter = p_Age.HasValue ?
                new ObjectParameter("P_Age", p_Age) :
                new ObjectParameter("P_Age", typeof(int));
    
            var p_PhoneParameter = p_Phone.HasValue ?
                new ObjectParameter("P_Phone", p_Phone) :
                new ObjectParameter("P_Phone", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CreateCustomer", p_CustomerNameParameter, p_LastNameParameter, p_CountryParameter, p_AgeParameter, p_PhoneParameter);
        }
    }
}
